version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - IP_REQUESTS_PER_SECOND=5
      - IP_BLOCK_DURATION_SECONDS=300
      - DEFAULT_TOKEN_REQUESTS_PER_SECOND=10
      - DEFAULT_TOKEN_BLOCK_DURATION_SECONDS=300
      - SERVER_PORT=8080
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 